export const personData = [
  {
    id: 1,
    first_name: 'Pietra',
    last_name: 'Guilleton',
    email: 'pguilleton0@barnesandnoble.com',
    gender: 'Female',
    ip_address: '173.88.80.30',
  },
  {
    id: 2,
    first_name: 'Winn',
    last_name: 'Beevens',
    email: 'wbeevens1@zimbio.com',
    gender: 'Male',
    ip_address: '0.152.177.63',
  },
  {
    id: 3,
    first_name: 'Carroll',
    last_name: 'Heskey',
    email: 'cheskey2@yellowbook.com',
    gender: 'Female',
    ip_address: '44.216.239.64',
  },
  {
    id: 4,
    first_name: 'Sigismond',
    last_name: 'Vasichev',
    email: 'svasichev3@list-manage.com',
    gender: 'Male',
    ip_address: '116.50.67.243',
  },
  {
    id: 5,
    first_name: 'Moe',
    last_name: 'Neeves',
    email: 'mneeves4@arizona.edu',
    gender: 'Male',
    ip_address: '104.15.112.153',
  },
  {
    id: 6,
    first_name: 'Gerardo',
    last_name: 'Wigsell',
    email: 'gwigsell5@rediff.com',
    gender: 'Non-binary',
    ip_address: '234.61.164.244',
  },
  {
    id: 7,
    first_name: 'Trudi',
    last_name: 'Stanluck',
    email: 'tstanluck6@pcworld.com',
    gender: 'Female',
    ip_address: '12.141.123.79',
  },
  {
    id: 8,
    first_name: 'Joseph',
    last_name: 'Nussey',
    email: 'jnussey7@upenn.edu',
    gender: 'Male',
    ip_address: '76.153.137.178',
  },
  {
    id: 9,
    first_name: 'Anallise',
    last_name: 'Renish',
    email: 'arenish8@google.com.au',
    gender: 'Female',
    ip_address: '164.166.245.168',
  },
  {
    id: 10,
    first_name: 'Parsifal',
    last_name: 'Mistry',
    email: 'pmistry9@sourceforge.net',
    gender: 'Male',
    ip_address: '97.22.232.116',
  },
];
